name = "Wahoo"
uuid = "34ee53bd-d3f2-451a-8e30-9c0767249144"
authors = ["Andreas Scheidegger"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
